---
title: "dplyr pipes"
author: "Xiao Shi"
date: "September 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r data import}
litters_data = read_csv(file = "./data/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)
sas_pup = read_csv(file = "./data/FAS_pups.csv", col_types = 'ciiiii')
sas_pup = janitor::clean_names(sas_pup)
```
## Select Variables
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
select(litters_data, group:gd_of_birth)
select(litters_data, -pups_survive)
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number) # change name
select(litters_data, litter_number, group, everything()) # change order
select(litters_data, group, everything())
```

## Select_helpers
```{r}
select(litters_data,starts_with("gd"))
select(litters_data,litter_number, starts_with("pup"))

```

## In class exercise
litter number, sex, and PD ears
```{r}
selected_pup = select(sas_pup, contains("litter_number"), starts_with("sex"), pd_ears)
```

## filter ##
